/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package ihome.proto.lightside;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface LightProto {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"LightProto\",\"namespace\":\"ihome.proto.lightside\",\"types\":[],\"messages\":{\"send_state\":{\"request\":[],\"response\":\"string\"},\"switch_state\":{\"request\":[],\"response\":\"string\"}}}");
  java.lang.CharSequence send_state() throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence switch_state() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends LightProto {
    public static final org.apache.avro.Protocol PROTOCOL = ihome.proto.lightside.LightProto.PROTOCOL;
    void send_state(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void switch_state(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}