/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package ihome.proto.fridgeside;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface FridgeProto {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"FridgeProto\",\"namespace\":\"ihome.proto.fridgeside\",\"types\":[],\"messages\":{\"send_current_items\":{\"request\":[],\"response\":\"string\"},\"send_all_items\":{\"request\":[],\"response\":\"string\"}}}");
  java.lang.CharSequence send_current_items() throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence send_all_items() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends FridgeProto {
    public static final org.apache.avro.Protocol PROTOCOL = ihome.proto.fridgeside.FridgeProto.PROTOCOL;
    void send_current_items(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void send_all_items(org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}