/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package ihome.proto.userside;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface UserProto {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"UserProto\",\"namespace\":\"ihome.proto.userside\",\"types\":[],\"messages\":{\"update_controller\":{\"request\":[{\"name\":\"jsonController\",\"type\":\"string\"}],\"response\":\"string\"},\"notify_empty_fridge\":{\"request\":[{\"name\":\"fid\",\"type\":\"int\"}],\"response\":\"int\"},\"receiveElection\":{\"request\":[{\"name\":\"receivedID\",\"type\":\"int\"}],\"response\":\"string\"},\"receiveElected\":{\"request\":[{\"name\":\"serverIP\",\"type\":\"string\"},{\"name\":\"port\",\"type\":\"int\"},{\"name\":\"serverID\",\"type\":\"int\"}],\"response\":\"string\"},\"ReceiveCoord\":{\"request\":[{\"name\":\"server_ip\",\"type\":\"string\"},{\"name\":\"port\",\"type\":\"int\"}],\"response\":\"int\"},\"notify_user_enters\":{\"request\":[{\"name\":\"uid\",\"type\":\"int\"}],\"response\":\"int\"},\"notify_user_leaves\":{\"request\":[{\"name\":\"uid\",\"type\":\"int\"}],\"response\":\"int\"}}}");
  java.lang.CharSequence update_controller(java.lang.CharSequence jsonController) throws org.apache.avro.AvroRemoteException;
  int notify_empty_fridge(int fid) throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence receiveElection(int receivedID) throws org.apache.avro.AvroRemoteException;
  java.lang.CharSequence receiveElected(java.lang.CharSequence serverIP, int port, int serverID) throws org.apache.avro.AvroRemoteException;
  int ReceiveCoord(java.lang.CharSequence server_ip, int port) throws org.apache.avro.AvroRemoteException;
  int notify_user_enters(int uid) throws org.apache.avro.AvroRemoteException;
  int notify_user_leaves(int uid) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends UserProto {
    public static final org.apache.avro.Protocol PROTOCOL = ihome.proto.userside.UserProto.PROTOCOL;
    void update_controller(java.lang.CharSequence jsonController, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void notify_empty_fridge(int fid, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void receiveElection(int receivedID, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void receiveElected(java.lang.CharSequence serverIP, int port, int serverID, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    void ReceiveCoord(java.lang.CharSequence server_ip, int port, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void notify_user_enters(int uid, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void notify_user_leaves(int uid, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}